#!/bin/bash

task="A"
directory="tasks"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -d)
            directory="$2"
            shift 2
            ;;
        *)
            task="$1"
            shift 1
            ;;
    esac
done

mkdir -p bin
stay="echo done; bash -c \"read var\""
gnome-terminal -- bash -c "g++ -std=c++17 -Wall -Og -g $directory/$task.cpp -o bin/$task; $stay;"
