#!/bin/bash

task="A"
directory="tasks"
#flags="-O2 -Wall -Wextra"
flags="-O2 -Wall -Wextra -Wshadow -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -Wshift-overflow=2"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -d)
            directory="$2"
            shift 2
            ;;
        -o)
            flags="-Wall -g"
            shift 1
            ;;
        *)
            task="$1"
            shift 1
            ;;
    esac
done

mkdir -p bin
stay="echo done; bash -c \"read var\""
gnome-terminal -- bash -c "g++ -std=c++17 $flags $directory/$task.cpp -o bin/$task; $stay;"
