#!/bin/bash

range=6
initlang="cpp"

while [[ $# -gt 0 ]]
do    
    option="$1"
    case $option in
        -cpp)
            initlang="cpp"
            shift 1
            ;;
        -rs)
            initlang="rust"
            shift 1
            ;;
        -py)
            initlang="python"
            shift 1
            ;;
        *)
            if [[ $1 =~ [0-9] ]]
            then
                range=$(( 1+($1-1)%26 ))
            else
                letter=$(echo $1|head -c 1|tr '[:upper:]' '[:lower:]')
                range=$(printf "%d" "'$letter")
                range=$(( 1+($range-97)%26 ))
            fi
            shift 1
            ;;
    esac
done

mkdir -p tests
mkdir -p tasks
mkdir -p old
mkdir -p old/old0
mkdir -p old/old1
mkdir -p old/old2
mkdir -p old/old3
mkdir -p old/old4
mkdir -p rust/src
touch rust/src/main.rs

rm -rf old/old4/*
cp -rf old/old3/* old/old4
rm -rf old/old3/*
cp -rf old/old2/* old/old3
rm -rf old/old2/*
cp -rf old/old1/* old/old2
rm -rf old/old1/*
cp -rf old/old0/* old/old1
rm -rf old/old0/*
cp -rf tasks tests old/old0

rm -rf tasks/*
rm -rf tests/*
mkdir -p tasks/cpp
mkdir -p tasks/rust
mkdir -p tasks/python

alphabet=( {A..Z} )

for ((i=0; i<range; i++)) 
do
    cp lib/cpp/template.cpp tasks/cpp/${alphabet[i]}.cpp
    cp lib/rs/template.rs tasks/rust/${alphabet[i]}.rs
    touch tasks/python/${alphabet[i]}.py
done

vim -S dev/.vimrc -p tasks/${initlang}/*

