#!/bin/bash

editor="vim"
initlang="cpp"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -g)
            editor="gedit"
            shift 1
            ;;
        -rs)
            initlang="rust"
            shift 1
            ;;
        -py)
            initlang="python"
            shift 1
            ;;
    esac
done

case $editor in
    vim)
        vim -S dev/.vimrc -p tasks/${initlang}/*
        ;;
    gedit)
        gedit tasks/${initlang}/*
        ;;
esac
