#!/bin/bash

editor="vim"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -g)
            editor="gedit"
            shift 1
            ;;
    esac
done

case $editor in
    vim)
        vim -S dev/.vimrc -p tasks/*
        ;;
    gedit)
        gedit tasks/*
        ;;
esac
