#!/bin/bash

task="A"
language="cpp"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -l)
            language="$2"
            shift 2
            ;;
        -t)
            task="$2"
            shift 2
            ;;
        *)
            task="$1"
            shift 1
            ;;
    esac
done

stay="bash -c \"read var\""

case $language in
    cpp)
        gnome-terminal -- bash -c "time bin/$task; $stay;"
        ;;
    rust)
        gnome-terminal -- bash -c "time bin/$task; $stay;"
        ;;
    python)
        gnome-terminal -- bash -c "time python3 tasks/python/$task.py; $stay;"
        ;;
esac
