#!/bin/bash

task="A"
language="cpp"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -l)
            language="$2"
            shift 2
            ;;
        -t)
            task="$2"
            shift 2
            ;;
        *)
            task="$1"
            shift 1
            ;;
    esac
done

stay="bash -c \"read var\""

cases=()
while IFS=  read -r -d $'\0'; do
    cases+=("$REPLY")
done < <(find ./tests -name "*${task}*.txt" -print0)

for tk in "${cases[@]}"
do
    case $language in
        cpp)
            gnome-terminal -- bash -c "cat $tk && time bin/$task < $tk; $stay;"
            ;;
        rust)
            gnome-terminal -- bash -c "cat $tk && time bin/$task < $tk; $stay;"
            ;;
        python)
            gnome-terminal -- bash -c "cat $tk && time pypy3 tasks/python/$task.py < $tk; $stay;"
            ;;
    esac
done
