#!/bin/bash

date=`date +%Y-%m-%d` 
language="cpp"
task="A"
extension="cpp"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -l)
            language="$2"
            shift 2
            ;;
        -t)
            task="$2"
            shift 2
            ;;
        *)
            task="$1"
            shift 1
            ;;
    esac
done

case $language in
    cpp)
        extension="cpp"
        ;;
    rust)
        extension="rs"
        ;;
    python)
        extension="py"
        ;;
esac

mkdir -p upsolve
cp tasks/$language/$task.$extension upsolve/$task-$date.$extension

