#!/bin/bash

if [[ $# -gt 0 ]]
then
    if [[ $1 =~ [0-9] ]]
    then
        range=$(( 1+($1-1)%26 ))
    else
        letter=$(echo $1|head -c 1|tr '[:upper:]' '[:lower:]')
        range=$(printf "%d" "'$letter")
        range=$(( 1+($range-97)%26 ))
    fi
else
    range=6
fi


mkdir -p tasks
mkdir -p tests
rm -f tasks/*
rm -f tests/*

alphabet=( {A..Z} )
for ((i=0; i<range; i++)) 
do
    cp lib/template.cpp tasks/${alphabet[i]}.cpp
done

vim -S .vimrc -p tasks/*

