#!/bin/bash

directory="tasks"
copy="lib/template.cpp"
paste="A"

while [[ $# -gt 0 ]]
do
    option="$1"
    case $option in
        -d)
            directory="$2"
            shift 2
            ;;
        -c)
            copy="$2"
            shift 2
            ;;
        -p)
            paste="$2"
            shift 2
            ;;
    esac
done

cat $copy >> $directory/$paste.cpp
